### ISSUE TITLE
Incorrect comment symbol in puppet language definition

### ISSUE THREAD

**Issue by aeschli** [blindly/vscode-puppet#1]
_From @mikemimik on December 4, 2015 7:14_

Conditions
- file has 'puppet' selected as language mode

Action
- using key bound to `editor.action.commentLine`

Result
- line is commented with `//`

Expectation
- line commented with `#`

_Copied from original issue: Microsoft/vscode#1002_

**Comment by aeschli** [comment]
Comment tokens are configured in `puppet.configuration.json`

**Comment by mikemimik** [comment]
@aeschli Thanks for the reference and point in the correct direction.

**Comment by dteirney** [comment]
Any chance this can be fixed so it's correct out-of-the-box?

**Comment by mikemimik** [comment]
I submitted a pull request #5

**Comment by blindly** [comment]
This was integrated
